### ISSUE TITLE
Doesn't work with objects

### ISSUE THREAD

**Issue by arvsrn** [bryanmylee/svelte-previous#14] opened 2024-06-10 09:31 UTC
When requireChange is set to true, the previous value remains null. When it's false, the previous value and current value are the same.

**Comment by bryanmylee** [comment] 2024-09-03 12:54
Hey, sorry I missed this previously, but this is by design, as equality is determined with `===`.

When `requireChange` is false, both values will be equal due to Svelte assigning to `currentValue` multiple times.

When `requireChange` is true, the object's reference is probably still the same, so `a1 === a2` and therefore no update is emitted.

```ts
const a1 = { name: "arvsrn" };
const a2 = a1;
a1.name = "bryanmylee";
a1 === a2 // true
```

To work around this, you need to pass an `isEqual` function.

```ts
const [current, previous] = withPrevious(a1, {
  requireChange: true,
  isEqual: (a, b) => a.name === b.name,
});
```

It is also possible to use [lodash.isequal](https://www.npmjs.com/package/lodash.isequal).

**Closed as completed by bryanmylee** 2024-09-03 12:54 UTC
